import path from "node:path";
import type { EditorGenerator } from "../../core/types.ts";

export const helixGenerator: EditorGenerator = {
  id: "helix",
  displayName: "Helix",
  fileExtHint: "toml",
  async generate(theme, context) {
    const toml = `# Auto-generated by theme engine\n\n"ui.background" = "${theme.ui.bg.base}"\n"ui.text" = "${theme.semantic.syntax.text}"\n"ui.cursor" = { fg = "${theme.ui.bg.base}", bg = "${theme.ui.editor.cursor}" }\n"ui.selection" = { bg = "${theme.ui.editor.selection}" }\n"ui.linenr" = "${theme.ui.editor.lineNumber}"\n"ui.linenr.selected" = "${theme.ui.editor.lineNumberActive}"\n\n"comment" = { fg = "${theme.semantic.syntax.comment}", modifiers = ["italic"] }\n"keyword" = "${theme.semantic.syntax.keyword}"\n"string" = "${theme.semantic.syntax.string}"\n"function" = "${theme.semantic.syntax.function}"\n"type" = "${theme.semantic.syntax.type}"\n"variable" = "${theme.semantic.syntax.variable}"\n`;

    return [
      {
        path: path.join(context.outDir, "helix", `${theme.id}-${theme.variation}.toml`),
        contents: toml
      }
    ];
  }
};
