import path from "node:path";
import type { EditorGenerator } from "../../core/types.ts";

export const neovimGenerator: EditorGenerator = {
  id: "neovim",
  displayName: "Neovim",
  fileExtHint: "lua",
  async generate(theme, context) {
    const lua = `-- Auto-generated by theme engine\nreturn {\n  normal = {\n    bg = "${theme.ui.bg.base}",\n    fg = "${theme.semantic.syntax.text}"\n  },\n  cursorline = { bg = "${theme.ui.editor.currentLine}" },\n  visual = { bg = "${theme.ui.editor.selection}" },\n  comment = { fg = "${theme.semantic.syntax.comment}" },\n  keyword = { fg = "${theme.semantic.syntax.keyword}" },\n  string = { fg = "${theme.semantic.syntax.string}" },\n  function_ = { fg = "${theme.semantic.syntax.function}" },\n  type = { fg = "${theme.semantic.syntax.type}" },\n  diagnostic = {\n    error = "${theme.semantic.diagnostics.error}",\n    warn = "${theme.semantic.diagnostics.warning}",\n    info = "${theme.semantic.diagnostics.info}",\n    hint = "${theme.semantic.diagnostics.hint}"\n  }\n}\n`;

    return [
      {
        path: path.join(context.outDir, "neovim", `${theme.id}-${theme.variation}.lua`),
        contents: lua
      }
    ];
  }
};
